MaggieAppleton/digital-gardeners

README.md
=> Add org-roam tutorial

README.md
* link to a more canonical Webmention source
* Sub-tools for TiddlyWiki
* Additional articles
* typo
* other public examples and systems
=> additional resources, articles, and examples

README.md
~1200 pages on different topics
=> added my own garden

README.md
Great set of resources Maggie!  Can I be on the list of gardeners?
=> 🙋‍♂️ I'm a digital gardener

README.md
=> fix Swyx’s listed site generator :)

README.md
Hey Maggie!
I stumbled upon this tool some days ago and later on, I found out about this repo. Coincidence? 😛
=> Added an extra tool for gardening

README.md
Hi, I have a site I just redid and set up a digital garden/diary in the "notes" section of the site. I use vim with vimwiki plugin to write it.
=> add Steve Dondley to directory

README.md
=> Org Roam Description

README.md
Hi Maggie, I love this repo!
I'd like to add myself here 🙏
=> Add Scott's garden

README.md
Added my personal digital garden to the list with notes on coding, note taking, personal knowledge management and other random thoughts.
=> Added my Second Brain

README.md
This pull request fixes a typo in Andy Matuschak's name and adds a row for my digital garden.
=> Fix typo & add Maxime Vaillancourt

README.md
Thanks 💚
The wiki is open source too, here: https://github.com/nikitavoloboev/knowledge
=> Add my wiki 🌿

README.md
Hi there! I finally dared to join the digital garden community, which I've been quietly observing from afar.
=> Submit my Digital Garden to the list

README.md
Link to the web version of my digital garden.
=> Adding my digital garden

README.md
Thank you for the inspiration!
=> Add foamy-next starter template and my garden

README.md
Adding [Neuron](https://github.com/srid/neuron) to the list of public-garden tools.
=> Add Neuron

README.md
Change from NextJS to Gatsby + MDX. 
As it can be seen on his repository: https://github.com/joelhooks/joelhooks-com
=> Update Joel Hooks' framework

README.md
style: remove trailing spaces in multiple lines
=> feat: add Blue Book digital garden

README.md
=> Add 5 no code digital gardening article

README.md
Hi!
I came across this resource. Is it okay if I add my own [personal wiki](https://pbat.ch/wiki) to it?
It's written using a custom wiki engine I made called [weewiki](https://pbat.ch/wiki/weewiki/).
Thanks!
-P
=> add paul batchelor's wiki

README.md
Self-submission. Hopefully self-explanatory.
=> Add Soren Bjornstad's Zettelkasten

README.md
Hi! I noticed that your [v2 repo](https://github.com/MaggieAppleton/maggieappleton.com-V2) is using Next.js and then noticed this 😀
=> Update Maggie in Garden Directory

README.md
My working notes are not a sub-domain, sub-directory.
=> URL Update

README.md
Went ahead and sorted the items in that sub-section alphabetically to prevent any implication of hierarchy.
=> add The Archive
